server:
  port: 8761

eureka:
   instance:
      hostname: localhost
   client:
      fetch-registry: false
      register-with-eureka: false

management:
   endpoints:
      web:
         exposure:
            include: "*"

spring:
   application:
      name: discovery-server    
